# Generated by Django 2.2.4 on 2022-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='website',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
