# Generated by Django 2.2.4 on 2022-09-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.CharField(help_text='Entre o nome do filme',max_length=100)),
                ('review', models.CharField(help_text='Escreva sua review', max_length=500)),
                ('nota', models.IntegerField(help_text='Qual nota você da?'))
            ],
        )
    ]
