# Generated by Django 2.2.4 on 2022-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='FilmeReview',
            name='website',
            field=models.URLField(null=True),
        )
    ]
