# Generated by Django 4.1.3 on 2022-11-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmes', '0002_review_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmereview',
            name='website',
        ),
        migrations.AlterField(
            model_name='filmereview',
            name='nota',
            field=models.IntegerField(help_text='Qual nota você da?', max_length=5),
        ),
    ]
